Main to merge
linuskar/TEK830-Digitalization-and-AI-in-practice-Group-6 pull request #58
Opened 2024-10-22 15:02 UTC by Gabriel2000001

All frontend work is done, product recommendation functionality to be added

2024-10-22 16:22 UTC, Caramajau requested changes
Before going into detail about the changes in the code, I believe there are three things that need to be changed:
- The app slideshow should not have yellow text and yellow buttons, considering that the rest of the program uses white text and white buttons. It is important to have a consistent theme throughtout the app. 
- The notification page should be able to display the exact notification that was sent and not a generic one. By letting notification history be a notification listener and changing the arraylist to have notfications instead of AnchorPanes.  This change should make it possible to create notifications similar to how it is done in Notification controller. Of course, for notification page instead of doing the animation it would instead add it to the notification page. (Right now, since notification history is using JavaFX classes it is technically a logical view, which should be a model).
- Thirdly, it is important to remove debug statements before merging to main.

2024-10-22 16:28 UTC, Caramajau commented on src/main/java/org/team6/controller/EnergyPage2Controller.java
EnergyPage2Controller is a confusing name. Give it a more descriptive name of what it actually is. For instance "EnergyInsightsMainPageController"?

2024-10-22 16:29 UTC, Caramajau commented on src/main/java/org/team6/controller/EnergyPage3Controller.java
EnergyPage2Controller is a confusing name. Give it a more descriptive name of what it actually is. For instance "EnergyInsightsGraphController"?

2024-10-22 16:31 UTC, Caramajau commented on src/main/java/org/team6/controller/NotificationController.java
> +    public void setNotificationHistory(NotificationHistory notificationHistory){
By being able to make notification history a NotificationListener this dependency should not be necessary.

2024-10-22 16:34 UTC, Caramajau commented on src/main/java/org/team6/controller/NotificationController.java
> +        if(notificationPane.isVisible()){
This check probably becomes unncessary if notification history would be a listener. I'm guessing it exists currently because the notification pane is reused between different notifications.

2024-10-22 16:38 UTC, Caramajau commented on src/main/java/org/team6/controller/NotificationPageController.java
> +    public void addNotificationToVbox() throws IOException {
Could be private. Also is the vbox only updated when switching between visible and not visible, not when new notifications are sent?

2024-10-22 16:38 UTC, Caramajau commented on src/main/java/org/team6/controller/NotificationPageController.java
> +        System.out.println(notificationText);
Example of debuging print.

2024-10-22 16:39 UTC, Caramajau commented on src/main/java/org/team6/controller/NotificationPageController.java
> +            System.out.println("notificationHistoryVBox is null!");
This kind of print is fine in my opinion since it is more of a log that can make it easier to debug in the future.

2024-10-22 16:41 UTC, Caramajau commented on src/main/java/org/team6/controller/SettingsPageController.java
> +import javafx.scene.control.*;
Said this in a previous PR, but I prefer to see single imports. Makes it easier to read the dependencies. Although there are advantages and disadvantages to both versions.

2024-10-22 16:44 UTC, Caramajau commented on src/main/java/org/team6/model/NotificationHistory.java
> +        private ArrayList<AnchorPane> notificationArray = new ArrayList<>();
Could be a final List as a static type instead of ArrayList. As said in a previous comment, it makes more sense to let NotificationHistory to be a listener with Notification in the ArrayList rather than relying on a JavaFX component such as an AnchorPane. JavaFX stuff makes more sense in the view.

2024-10-22 16:44 UTC, Caramajau commented on src/main/java/org/team6/model/NotificationHistory.java
> +        public ArrayList<AnchorPane> getNotificationList(){
Can return a List insteaf of an ArrayList

2024-10-22 16:45 UTC, Caramajau commented on src/main/java/org/team6/view/PageStarter.java
> +        primaryStage.setTitle("Energy overview");
In the English version of the app it is called Energy Insights and not overview.

2024-10-22 16:46 UTC, Caramajau commented on src/main/java/org/team6/view/PageStarter.java
> +            String notificationText = notificationController.getNotificationText();
What is the purpose of notification text?

2024-10-22 16:51 UTC, Caramajau commented on src/main/resources/org/team6/view/EnergyPage3.fxml
> +                        <Image url="@../../../../../../../../Users/shado/Downloads/image_transparent.png" />
It seems like you have accidentelly chosen an image that you have saved locally on your PC, rather than in the project. It gives a warning in Scene Builder.

2024-10-22 16:58 UTC, Caramajau commented
If you want any help with making NotificationHistory a NotificationListener and what refractorings that allows to make, I can help.

2024-10-22 17:03 UTC, Caramajau commented on src/main/java/org/team6/controller/NotificationController.java
> +    public Text returnText(){
Saw now that it is unused?

2024-10-22 17:13 UTC, Caramajau commented on src/main/resources/org/team6/view/AppTutorialPage.fxml
> +            <Label fx:id="counterLabel" layoutX="155.0" layoutY="335.0" text="99/99" textFill="WHITE" AnchorPane.leftAnchor="155.0" AnchorPane.rightAnchor="154.0" AnchorPane.topAnchor="335.0" />
I believe we said it made more sense for the counter to be in the top right corner rather than under the image. Can say that there is a risk right now that the counter text and info text overlap for slides with longer info texts.

2024-10-22 17:17 UTC, Caramajau commented on src/main/resources/org/team6/view/AppTutorialPage.fxml
> +            <Button fx:id="forwardButton" mnemonicParsing="false" onAction="#handleForwardOnAction" text="▶" AnchorPane.bottomAnchor="16.0" AnchorPane.rightAnchor="16.0">
Is there any specific reasoning why the buttons have different heights? I feel like there would be more satisfying if alignment was done. https://uxengineer.com/principles-of-design/alignment

2024-10-22 19:38 UTC, linuskar requested changes
Rename mentions of Energy overview to Energy Insights. 

Also here rename Title for Productrecommendations to Recommendations. And the following text under to be "Take a look at our recommendations". As there will be more than just product recommendations but concepts of tip recommendations.

![image](https://github.com/user-attachments/assets/d82f2be8-02e2-4891-adfb-bf5cb4445771)

Also the back button when pressing one of the current price buttons for this following screen does not work. 
![image](https://github.com/user-attachments/assets/48c609d8-dca7-47fd-bcc1-5b7b2d31d47f)

2024-10-23 14:15 UTC, Sebbe213 commented on src/main/java/org/team6/controller/NotificationController.java
> +    public void setNotificationHistory(NotificationHistory notificationHistory){
We do not have a generic notification anymore, this is till needed but you can look into it if you want.

2024-10-23 14:20 UTC, Sebbe213 commented on src/main/java/org/team6/controller/NotificationPageController.java
> +    public void addNotificationToVbox() throws IOException {
It was not possible to make it private. Need to use it outside of the class.

2024-10-23 14:23 UTC, Sebbe213 commented on src/main/java/org/team6/model/NotificationHistory.java
> +        private ArrayList<AnchorPane> notificationArray = new ArrayList<>();
the current solution is functional, take a look at it and see if it can be improved.

2024-10-23 14:34 UTC, Sebbe213 commented on src/main/resources/org/team6/view/AppTutorialPage.fxml
> +            <Button fx:id="forwardButton" mnemonicParsing="false" onAction="#handleForwardOnAction" text="▶" AnchorPane.bottomAnchor="16.0" AnchorPane.rightAnchor="16.0">
It should already be aligned.

2024-10-23 15:08 UTC, linuskar requested changes
Change mentions of Energy overview to Energy Insights for this screen too. Change the button text to from "Get an energy overview" to like "See energy insights".
![image](https://github.com/user-attachments/assets/a0284a6b-e6c7-422d-8ef3-cfa746f4f54e)

2024-10-23 16:11 UTC, Caramajau commented on .gitignore
> +/src/main/resources/org/team6/view/Notification_page.fxml
Why did this happen?

2024-10-23 16:13 UTC, Caramajau commented on src/main/java/org/team6/controller/NotificationController.java
> +    NotificationPageController notificationPageController;
Looks like NotificationPageController is now unnecessary and its setter.

2024-10-23 16:13 UTC, Caramajau commented on src/main/java/org/team6/controller/NotificationController.java
> +    private NotificationHistory notificationHistory;
Looks like NotificationHistory is now unnecessary and its setter.

2024-10-23 16:18 UTC, Caramajau commented on src/main/resources/org/team6/view/AppTutorialPage.fxml
> +            <Button fx:id="forwardButton" mnemonicParsing="false" onAction="#handleForwardOnAction" text="▶" AnchorPane.bottomAnchor="16.0" AnchorPane.rightAnchor="16.0">
What I meant is that due to the height being different there is not alignment between buttons, yes they are on the same y value, but the top and bottoms of the buttons are not aligned.

2024-10-23 16:20 UTC, Caramajau commented on src/main/java/org/team6/controller/NotificationController.java
> +    private NotificationHistory notificationHistory;
I now see that in the solution that you came up with it is not unnecessary. The dependency could be removed by making notification history a notifications listener itself, but I guess this is ok.

2024-10-23 16:22 UTC, Caramajau commented on src/main/java/org/team6/controller/NotificationController.java
> +    NotificationPageController notificationPageController;
This was also not able to be removed in the current solution, but could at least be private I think.

2024-10-23 16:41 UTC, Caramajau commented on src/main/java/org/team6/model/NotificationHistory.java
> +        private ArrayList<AnchorPane> notificationArray = new ArrayList<>();
Right now it works like it should, but ideally notification history would itself be a notfication listener. But I think it is good enough considering that we're close to the end of the project.

2024-10-23 16:42 UTC, Caramajau commented on src/main/java/org/team6/controller/NotificationPageController.java
> +    public void addNotificationToVbox() throws IOException {
Ok, already indirectly written about it, but think that if notification history would itself be a listener than it would probably be able to be private. But I guess it's fine.

2024-10-25 08:09 UTC, Caramajau approved these changes

2024-10-25 08:10 UTC, linuskar approved these changes
cool

2024-10-25 08:10 UTC, merged